name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test-frontend:
    name: Run Web Client Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Install Playwright Browsers
        run: npm run playwright install --with-deps
        working-directory: web

      - name: Build web client
        run: npm run build
        working-directory: web

      - name: Start web client
        run: |
          nohup npm run start &
          npx wait-on http://localhost:5173
        working-directory: web

      - name: Run Playwright tests
        run: npm run test
        working-directory: web

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  test-backend:
    name: Run Server tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python env
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make venv
          make install
        working-directory: server

      - name: Run tests
        run: make test
        working-directory: server
