name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test-frontend:
    name: Run Web Client Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: cd web && npm install

      - name: Install Playwright Browsers
        run: npm run playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Confirm web client builds
        run: npm run build
  test-backend:
    name: Run Server tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python env
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: cd server && make venv && make install

      - name: Run tests
        run: make test
